import os
import pandas as pd
import xlsxwriter

#Search for excel files in my desktop
path = os.getcwd()
files = os.listdir(path)
files_lsx = [f for f in files if f[-3:] == 'lsx']

#appened the excelfile to a Data Frame
df = pd.DataFrame()
for f in files_lsx:
    data = pd.read_excel(f)
    df = df.append(data)

#Helper Columns to find Test Accs
df['AEDIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('AEDIDR')
df['AUDAUD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('AUDAUD')
df['AUDIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('AUDIDR')
df['AUDSGD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('AUDSGD')
df['AUDUSD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('AUDUSD')
df['CADIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('CADIDR')
df['CADSGD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('CADSGD')
df['CHFIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('CHFIDR')
df['CNYCNY'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('CNYCNY')
df['CNYIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('CNYIDR')
df['EUREUR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('EUREUR')
df['EURIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('EURIDR')
df['EURSGD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('EURSGD')
df['EURUSD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('EURUSD')
df['GBPGBP'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('GBPGBP')
df['GBPIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('GBPIDR')
df['GBPSGD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('GBPSGD')
df['GBPUSD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('GBPUSD')
df['HKDHKD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('HKDHKD')
df['HKDIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('HKDIDR')
df['IDRIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('IDRIDR')
df['IDRVND'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('IDRVND')
df['INRIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('INRIDR')
df['INRINR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('INRINR')
df['JPYIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('JPYIDR')
df['JPYJPY'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('JPYJPY')
df['KRWIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('KRWIDR')
df['KRWKRW'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('KRWKRW')
df['MYRIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('MYRIDR')
df['NZDIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('NZDIDR')
df['NZDSGD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('NZDSGD')
df['PHPIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('PHPIDR')
df['SARIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SARIDR')
df['SGDCNY'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDCNY')
df['SGDHKD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDHKD')
df['SGDIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDIDR')
df['SGDINR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDINR')
df['SGDJPY'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDJPY')
df['SGDLKR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDLKR')
df['SGDMYR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDMYR')
df['SGDNOK'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDNOK')
df['SGDNZD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDNZD')
df['SGDPHP'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDPHP')
df['SGDSGD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDSGD')
df['SGDTHB'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDTHB')
df['SGDVND'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('SGDVND')
df['THBIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('THBIDR')
df['TRYIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('TRYIDR')
df['USDCAD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDCAD')
df['USDCNY'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDCNY')
df['USDHKD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDHKD')
df['USDIDR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDIDR')
df['USDINR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDINR')
df['USDJPY'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDJPY')
df['USDMYR'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDMYR')
df['USDPHP'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDPHP')
df['USDSGD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDSGD')
df['USDTHB'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDTHB')
df['USDVND'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDVND')
df['USDUSD'] = df['FIRST_3MONTHS_CURRENCY_PAIRS'].str.contains('USDUSD')

df.to_excel('finance_cleaned.xlsx',index = False)

print("Congrats! Finance Files Cleaned!")
